### ISSUE TITLE
Hoofdstuk 11: Basic Shell Scripting / Command Line Arguments

### ISSUE THREAD

**Issue by MichielDecoster** [BioBoost/course_linux_essentials#1]
Hey Nico

Ik denk dat ik een foutje heb gevonden onder hoofdstuk 11: Basic Shell Scripting / Command Line Arguments.

![Capture](https://user-images.githubusercontent.com/36663402/71074586-d585c400-2182-11ea-94d9-7c30ab999fc1.PNG)

bij `First:` moeten deze niet ` ./hello` zijn?

**Comment by BioBoost** [comment]
Inderdaad. Zin om het aan te passen en een pull-request te doen ? Goede oefening om eens te proberen zou ik zeggen :).

Je maakt gewoon een fork van de repo hier op GitHub. Dan clone je de repo lokaal. Daar maak je vervolgens een branch aan met `git checkout -b fix-script-output`

Dan doe je de aanpassing en commit je alles. Je pusht dan je branch naar je eigen repo met: `git push origin fix-script-output`. Dan zou je deze moeten kunnen raadplegen op GitHub.

Vervolgens maak je op GitHub een pull-request en selecteer je de fix branch en geef je korte beschrijving van probleem en oplossing. Eens klaar, indienen en wachten op mijn goedkeuring :).

Moest er iets niet lukken geef je hier maar seintje.

**Comment by MichielDecoster** [comment]
Hey Nico

Het is volgens mij gelukt, maar heb wel een typo in de commit message.

**Comment by BioBoost** [comment]
Mooi :).

Geen probleem van typo. Als je niet had gepushed had je het kunnen fixen met `git commit --amend`, daarmee kan je de laatste commit nog aanpassen. Maar je kan dit best niet meer doen als je gepushed hebt (je herschrijft hiermee eigenlijk de historiek van git).

Heb je de pull request ook gedaan want die zie ik niet ...

**Comment by MichielDecoster** [comment]
Ik was inderdaad vergeten de pull request te doen!
Heb ik nu gedaan
